### ISSUE TITLE
add pluggable ModelView to datapoints endpoint 

### ISSUE THREAD

**Issue by epogrebnyak** [mini-kep/db#69]
http://flask.pocoo.org/docs/0.12/views/#method-views-for-apis

**Comment by epogrebnyak** [comment]
Code under review: 

https://github.com/mini-kep/db/blob/079eb56e835bcefb0f6feeb0a6a3f2f6f5dd6a71/db/api/views.py#L63-L190

**Comment by epogrebnyak** [comment]
Functionality:
- ```api/datapoints``` has POST, GET DELETE methods to manipulate and select data 

Scope of review:
- [ ] are views monted ok?
- [ ] shoudl we move to pluggable view as they have clean method names?
- [ ] is underlying queries.DatapointOperations class ok
- [ ] are tests ok for ```api/datapoints```
- [ ] what should be a complete data cycle scenario for this endpoint (no data, upload, query, delete something, upload replacement, query again). 


Need also review underlying queries.DataOperations class:

**Comment by epogrebnyak** [comment]
Current problem: how to mount ModelViews in blueprint? See https://github.com/mini-kep/db/blob/234134ed12fcc28426af71771c5bcad48db7da1f/db/api/views.py#L126-L128

**Comment by epogrebnyak** [comment]
Error stask for above is

```
C:\Users\Евгений\Documents\GitHub\mini-kep-db>python run_local.py
Traceback (most recent call last):
  File "run_local.py", line 9, in <module>
    app.register_blueprint(api_module)
  File "D:\Anaconda3\lib\site-packages\flask\app.py", line 64, in wrapper_func
    return f(self, *args, **kwargs)
  File "D:\Anaconda3\lib\site-packages\flask\app.py", line 951, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "D:\Anaconda3\lib\site-packages\flask\blueprints.py", line 154, in register
    deferred(state)
  File "D:\Anaconda3\lib\site-packages\flask\blueprints.py", line 173, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "D:\Anaconda3\lib\site-packages\flask\blueprints.py", line 76, in add_url_rule
    view_func, defaults=defaults, **options)
  File "D:\Anaconda3\lib\site-packages\flask\app.py", line 64, in wrapper_func
    return f(self, *args, **kwargs)
  File "D:\Anaconda3\lib\site-packages\flask\app.py", line 1046, in add_url_rule
    self.url_map.add(rule)
  File "D:\Anaconda3\lib\site-packages\werkzeug\routing.py", line 1207, in add
    rule.bind(self)
  File "D:\Anaconda3\lib\site-packages\werkzeug\routing.py", line 687, in bind
    self.compile()
  File "D:\Anaconda3\lib\site-packages\werkzeug\routing.py", line 737, in compile
    _build_regex(self.is_leaf and self.rule or self.rule.rstrip('/'))
  File "D:\Anaconda3\lib\site-packages\werkzeug\routing.py", line 727, in _build_regex
    variable, converter, c_args, c_kwargs)
  File "D:\Anaconda3\lib\site-packages\werkzeug\routing.py", line 695, in get_converter
    raise LookupError('the converter %r does not exist' % converter_name)
LookupError: the converter 'str' does not exist
```

**Comment by epogrebnyak** [comment]
In variable rules the string should be ```string```, not str. <http://flask.pocoo.org/docs/0.12/quickstart/#variable-rules>

**Comment by epogrebnyak** [comment]
Fixed by https://github.com/mini-kep/db/commit/1ead53a735dadd08a56d062b44f9e418bdd4cf50
